---
- hosts: all 
  become: True
  gather_facts: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      tags:
        - apt_get
      when: ansible_os_family=="Debian"
    - name: Install nginx on redhat family
      package:
        name: httpd
        state: present
      when: ansible_os_family=="RedHat"
    - name: Start httpd daemon
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family=="RedHat"
    - name: Create user Osei 
      user:
        name: Victor
        comment: Victor Osei
        shell: /bin/bash
    - name: Create group
      group:
        name: cloudteam
        state: present
    - name: Create index file
      file:
        path: /var/www/html/index.html
        state: touch
      register: file_output
      tags: 
        - a
    - name: Create directory
      file:
        path: /tmp/os
        state: directory
    - name: copy content to index
      copy:
        dest: file_output.diff.before.path
        content: 'This is created using Ansible'


